[SERVICE]
    Flush            1
    Daemon           Off
    Log_Level        info
    Parsers_File     parsers.conf

[INPUT]
    Name             tail
    Path             /var/log/service-request-api/*.json
    Tag              service-request-api
    Parser           json_line
    Refresh_Interval 2
    DB               /var/log/flb-db/service-request-api.db

[INPUT]
    Name             tail
    Path             /var/log/servicenow-consumer/*.json
    Tag              servicenow-consumer
    Parser           json_line
    Refresh_Interval 2
    DB               /var/log/flb-db/servicenow-consumer.db

[INPUT]
    Name             tail
    Path             /var/log/customer-db-consumer/*.json
    Tag              customer-db-consumer
    Parser           json_line
    Refresh_Interval 2
    DB               /var/log/flb-db/customer-db-consumer.db

[OUTPUT]
    Name             opensearch
    Match            *
    Host             opensearch
    Port             9200
    Logstash_Format  On
    Logstash_Prefix  tracebridge-logs
    Suppress_Type_Name On
    tls              Off
    Retry_Limit      False
